import { defineVerticalPack } from './verticalPackAuthoring';

export const vape420VerticalPackConfig = defineVerticalPack({
    id: 'vape-420',
    label: 'Vape/420',
    description: 'Current VSM vertical pack for vape, 420 accessories, and related catalog assumptions.',
    sections: [
        {
            slug: 'vape',
            label: 'Vape Collection',
            shortLabel: 'Vape',
            routePrefix: '/vape',
            description: 'Pods, l\u00edquidos, accesorios y todo lo que necesitas para vapear.',
            seoDescription: 'Explora toda nuestra colecci\u00f3n de vapeo: pods, l\u00edquidos, accesorios y m\u00e1s.',
            themeToken: 'vape',
        },
        {
            slug: '420',
            label: '420 Zone',
            shortLabel: '420',
            routePrefix: '/420',
            description: 'Herbal, grinders, papel, accesorios y m\u00e1s para tu sesi\u00f3n perfecta.',
            seoDescription: 'Descubre nuestra selecci\u00f3n completa de productos 420: herbal, accesorios y m\u00e1s.',
            themeToken: 'herbal',
        },
    ],
    categoryTaxonomyHints: [
        {
            slug: 'liquidos',
            label: 'Liquidos',
            sectionSlug: 'vape',
            fixtureImageKey: 'category-liquidos',
        },
        {
            slug: 'mods',
            label: 'Pods & Mods',
            sectionSlug: 'vape',
            fixtureImageKey: 'category-pods',
        },
        {
            slug: 'accesorios-vape',
            label: 'Accesorios Vape',
            sectionSlug: 'vape',
            fixtureImageKey: 'category-accesorios',
        },
        {
            slug: 'concentrados',
            label: 'Cannabis Premium',
            sectionSlug: '420',
            fixtureImageKey: 'category-cannabis',
        },
    ],
    productAttributeHints: [
        {
            categorySlug: 'disposables',
            sectionSlug: 'vape',
            attributes: ['Puffs', 'Capacidad', 'Bateria', 'Nicotina', 'Puerto de Carga'],
        },
        {
            categorySlug: 'vape-kits',
            sectionSlug: 'vape',
            attributes: ['Watts', 'Bateria', 'Capacidad', 'Resistencia Incluida', 'Puerto de Carga'],
        },
        {
            categorySlug: 'pods',
            sectionSlug: 'vape',
            attributes: ['Resistencia', 'Capacidad', 'Compatibilidad'],
        },
        {
            categorySlug: 'liquidos',
            sectionSlug: 'vape',
            attributes: ['Nicotina', 'VG/PG', 'Volumen'],
        },
        {
            categorySlug: 'flores',
            sectionSlug: '420',
            attributes: ['THC%', 'CBD%', 'Genetica', 'Efecto', 'Terpenos'],
        },
        {
            categorySlug: 'extractos',
            sectionSlug: '420',
            attributes: ['Concentracion', 'Metodo de Extraccion', 'Tipo', 'THC%'],
        },
        {
            categorySlug: 'parafernalia',
            sectionSlug: '420',
            attributes: ['Material', 'Tamano', 'Compatibilidad'],
        },
    ],
    attributeSchema: {
        suggestedSpecsByCategorySlug: {
            disposables: ['Puffs', 'Capacidad', 'Batería', 'Nicotina', 'Puerto de Carga'],
            'vape-kits': ['Watts', 'Batería', 'Capacidad', 'Resistencia Incluida', 'Puerto de Carga'],
            pods: ['Resistencia', 'Capacidad', 'Compatibilidad'],
            liquidos: ['Nicotina', 'VG/PG', 'Volumen'],
            'accesorios-vape': ['Compatibilidad', 'Material'],
            flores: ['THC%', 'CBD%', 'Genética', 'Efecto', 'Terpenos'],
            extractos: ['Concentración', 'Método de Extracción', 'Tipo', 'THC%'],
            comestibles: ['Dosis por Porción', 'Total Cannabinoides', 'Sabor'],
            'vapes-420': ['Capacidad', 'Voltaje Variable', 'Batería', 'THC%'],
            parafernalia: ['Material', 'Tamaño', 'Compatibilidad'],
        },
        defaultSpecsBySectionSlug: {
            vape: ['Marca', 'Modelo', 'Color'],
            '420': ['Marca', 'Tipo', 'Efecto'],
        },
        specKeyNormalization: {
            watt: 'Watts',
            watts: 'Watts',
            vatios: 'Watts',
            wats: 'Watts',
            puf: 'Puffs',
            puff: 'Puffs',
            puffs: 'Puffs',
            hits: 'Puffs',
            nic: 'Nicotina',
            nicotine: 'Nicotina',
            nico: 'Nicotina',
            resistencia: 'Resistencia',
            ohm: 'Resistencia',
            ohms: 'Resistencia',
            coil: 'Resistencia',
            thc: 'THC%',
            'thc%': 'THC%',
            cbd: 'CBD%',
            'cbd%': 'CBD%',
            cannabinoides: 'Total Cannabinoides',
            terps: 'Terpenos',
            terpenos: 'Terpenos',
            battery: 'Batería',
            bateria: 'Batería',
            cap: 'Capacidad',
            capacity: 'Capacidad',
            size: 'Tamaño',
            material: 'Material',
            color: 'Color',
            marca: 'Marca',
            brand: 'Marca',
        },
    },
    compatibilityRuleLabels: [
        'Pods compatibles con equipo base',
        'Consumibles compatibles con kit o dispositivo',
        'Accesorios compatibles por material, tamano o conexion',
    ],
    recommendationRuleLabels: [
        'Alternativas por presupuesto dentro de la misma seccion',
        'Kitting de equipo base con consumibles',
        'Recuperacion de busqueda cuando no existe match exacto',
    ],
    legalPolicyCaveatLabels: [
        'Productos regulados por edad y jurisdiccion',
        'No prometer beneficios medicos',
        'No inventar disponibilidad, compatibilidad o tiempos de entrega',
    ],
    marketing: {
        homeHero: {
            primaryCopy: {
                title: 'Vapes y 420',
                subtitle: 'seleccionados',
                description:
                    'Productos importados con envíos por DHL desde Acapulco. Compra fácil, envío seguro y sin entregas personales.',
                tag: 'Envíos Nacionales',
            },
        },
        categoryShowcase: {
            fallbackCategories: [
                {
                    id: '1',
                    name: 'Líquidos',
                    slug: 'liquidos',
                    sectionSlug: 'vape',
                    iconName: 'Flame',
                    fallbackImagePath: '/images/storefront-fallbacks/category-liquidos.svg',
                    presetId: 'orange-red',
                },
                {
                    id: '2',
                    name: 'Pods & Mods',
                    slug: 'mods',
                    sectionSlug: 'vape',
                    iconName: 'Box',
                    fallbackImagePath: '/images/storefront-fallbacks/category-pods.svg',
                    presetId: 'blue-purple',
                },
                {
                    id: '3',
                    name: 'Cannabis Premium',
                    slug: 'concentrados',
                    sectionSlug: '420',
                    iconName: 'Leaf',
                    fallbackImagePath: '/images/storefront-fallbacks/category-cannabis.svg',
                    presetId: 'green-emerald',
                },
                {
                    id: '4',
                    name: 'Accesorios',
                    slug: 'accesorios-vape',
                    sectionSlug: 'vape',
                    iconName: 'Zap',
                    fallbackImagePath: '/images/storefront-fallbacks/category-accesorios.svg',
                    presetId: 'yellow-orange',
                },
            ],
        },
    },
    fixtureMetadata: {
        demoProductFamilies: ['Caliburn', 'Nova Pod', 'Mango Ice', 'Vape Pen 22mm'],
        demoCategorySlugs: ['liquidos', 'mods', 'concentrados', 'accesorios-vape'],
        fallbackImageKeys: ['category-liquidos', 'category-pods', 'category-cannabis', 'category-accesorios'],
    },
});
