-- ============================================================================
-- Vector Pipeline Down-Migration - Canonical 768d Alignment
-- ============================================================================
-- Context: the active Gemini embedding runtime path is capped at 768d.
-- This migration converges deployed environments to the executable 768d truth.
-- It intentionally does not pad vectors. Incompatible stored embeddings are
-- cleared during type down-migration and must be re-generated by the aligned
-- ingestion/runtime producers.
-- ============================================================================

create extension if not exists vector;

drop index if exists products_embedding_idx;
drop index if exists store_knowledge_embedding_idx;

do $$
declare
    products_embedding_type text;
    knowledge_embedding_type text;
begin
    select format_type(a.atttypid, a.atttypmod)
    into products_embedding_type
    from pg_attribute a
    join pg_class c on c.oid = a.attrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'products'
      and a.attname = 'embedding'
      and a.attnum > 0
      and not a.attisdropped;

    if products_embedding_type is not null and products_embedding_type <> 'vector(768)' then
        execute 'alter table public.products alter column embedding type vector(768) using null::vector(768)';
    elsif products_embedding_type = 'vector(768)' then
        execute 'alter table public.products alter column embedding type vector(768) using embedding::vector(768)';
    end if;

    select format_type(a.atttypid, a.atttypmod)
    into knowledge_embedding_type
    from pg_attribute a
    join pg_class c on c.oid = a.attrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'store_knowledge'
      and a.attname = 'embedding'
      and a.attnum > 0
      and not a.attisdropped;

    if knowledge_embedding_type is not null and knowledge_embedding_type <> 'vector(768)' then
        execute 'alter table public.store_knowledge alter column embedding type vector(768) using null::vector(768)';
    elsif knowledge_embedding_type = 'vector(768)' then
        execute 'alter table public.store_knowledge alter column embedding type vector(768) using embedding::vector(768)';
    end if;
end
$$;

create index if not exists products_embedding_idx on public.products
using ivfflat (embedding vector_cosine_ops)
with (lists = 100);

create index if not exists store_knowledge_embedding_idx
    on public.store_knowledge
    using hnsw (embedding vector_cosine_ops)
    with (m = 16, ef_construction = 64);

drop function if exists match_products(vector(768), float, int, int);
drop function if exists match_products(vector(3072), float, int, int);

create or replace function match_products (
  query_embedding vector(768),
  match_threshold float,
  match_count     int,
  min_stock       int default 0
)
returns table (
  id            uuid,
  name          text,
  slug          text,
  description   text,
  price         numeric,
  cover_image   text,
  section       text,
  similarity    float,
  ai_sales_note text,
  specs         jsonb
)
language plpgsql
as $$
begin
  return query
  select
    p.id,
    p.name,
    p.slug,
    p.description,
    p.price,
    p.cover_image,
    p.section::text as section,
    1 - (p.embedding <=> query_embedding) as similarity,
    p.ai_sales_note,
    p.specs
  from public.products p
  where p.embedding is not null
    and 1 - (p.embedding <=> query_embedding) > match_threshold
    and p.stock >= min_stock
    and p.status = 'active'
  order by p.embedding <=> query_embedding
  limit match_count;
end;
$$;

drop function if exists public.match_knowledge(vector(768), float, int, text);
drop function if exists public.match_knowledge(vector(1536), float, int, text);
drop function if exists public.match_knowledge(vector(3072), float, int, text);

create or replace function public.match_knowledge (
    query_embedding vector(768),
    match_threshold float default 0.70,
    match_count     int   default 3,
    filter_category text  default null
)
returns table (
    id         uuid,
    title      text,
    content    text,
    category   text,
    source_id  text,
    similarity float
)
language plpgsql
security definer
as $$
begin
    return query
    select
        k.id,
        k.title,
        k.content,
        k.category,
        k.source_id,
        1 - (k.embedding <=> query_embedding) as similarity
    from public.store_knowledge k
    where k.is_active = true
      and k.embedding is not null
      and 1 - (k.embedding <=> query_embedding) > match_threshold
      and (filter_category is null or k.category = filter_category)
    order by k.embedding <=> query_embedding
    limit match_count;
end;
$$;
